version: "3.5"
services:
  kibana:
    hostname: kibana
    image: kibana:7.3.2
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "5601:5601"
    volumes:
      - "/var/docker/kibana/log:/usr/share/kibana/logs"
      - "/var/docker/kibana/data:/usr/share/kibana/data"
    environment:
      - "server.name=kibana"
      - "server.host=0"
      - 'elasticsearch.hosts=[ "http://elasticsearch:9200" ]'
      - "xpack.monitoring.ui.container.elasticsearch.enabled=true"
    networks:
      - online
networks:
  online:
    external: true
    name: online
